# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chatapp_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.



import socket
import threading
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog, QApplication, QWidget, QMessageBox



class Ui_Client(object):
    def setupUi(self, Client):
        Client.setObjectName("Client")
        Client.resize(800, 600)
        Client.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(Client)
        self.centralwidget.setStyleSheet("QWidget#centralwidget\n"
"{background-color: qlineargradient(spread:pad, x1:0.0965909, y1:0.113636, x2:1, y2:1, stop:0 rgba(255, 238, 238, 255), stop:1 rgba(255, 255, 255, 255))};")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setMinimumSize(QtCore.QSize(300, 300))
        self.frame_3.setMaximumSize(QtCore.QSize(330, 300))
        self.frame_3.setBaseSize(QtCore.QSize(0, 0))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.formLayout = QtWidgets.QFormLayout(self.frame_3)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("border-radius:25px;\n"
"font: 15pt \"Algerian\";\n"
"")
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.ip_edit = QtWidgets.QLineEdit(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Adobe Heiti Std")
        font.setPointSize(12)
        self.ip_edit.setFont(font)
        self.ip_edit.setObjectName("ip_edit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ip_edit)
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("border-radius:25px;\n"
"font: 15pt \"Algerian\";\n"
"")
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.port_edit = QtWidgets.QLineEdit(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Adobe Heiti Std")
        font.setPointSize(12)
        self.port_edit.setFont(font)
        self.port_edit.setObjectName("port_edit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.port_edit)
        self.label_6 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("border-radius:30px;\n"
"font: 15pt \"方正姚体\";\n"
"")
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.username_edit = QtWidgets.QLineEdit(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Adobe Heiti Std")
        font.setPointSize(12)
        self.username_edit.setFont(font)
        self.username_edit.setObjectName("username_edit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.username_edit)
        self.login_button = QtWidgets.QPushButton(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.login_button.setFont(font)
        self.login_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.login_button.setStyleSheet("border-radius:25px;\n"
"font: 15pt \"方正姚体\";\n"
"background-color: #EBD8C3")
        self.login_button.setObjectName("login_button")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.login_button)
        self.logout_button = QtWidgets.QPushButton(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.logout_button.setFont(font)
        self.logout_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.logout_button.setStyleSheet("border-radius:25px;\n"
"font: 15pt \"方正姚体\";\n"
"background-color: #F7E9D7")
        self.logout_button.setObjectName("logout_button")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.logout_button)
        self.exit_button = QtWidgets.QPushButton(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.exit_button.setFont(font)
        self.exit_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exit_button.setStyleSheet("border-radius:25px;\n"
"font: 15pt \"方正姚体\";\n"
"background-color: #EBD8C3")
        self.exit_button.setObjectName("exit_button")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.SpanningRole, self.exit_button)
        self.horizontalLayout.addWidget(self.frame_3)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setStyleSheet("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.message_edit = QtWidgets.QTextEdit(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.message_edit.setFont(font)
        self.message_edit.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.message_edit.setObjectName("message_edit")
        self.gridLayout_2.addWidget(self.message_edit, 2, 0, 1, 1)
        self.info = QtWidgets.QTextBrowser(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.info.setFont(font)
        self.info.setObjectName("info")
        self.gridLayout_2.addWidget(self.info, 1, 0, 1, 1)
        self.send_message_button = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.send_message_button.setFont(font)
        self.send_message_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.send_message_button.setStyleSheet("border-radius:25px;\n"
"font: 15pt \"方正姚体\";\n"
"background-color: #EBD8C3")
        self.send_message_button.setObjectName("send_message_button")
        self.gridLayout_2.addWidget(self.send_message_button, 3, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setMaximumSize(QtCore.QSize(300, 300))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.formLayout_2 = QtWidgets.QFormLayout(self.frame)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_5 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("border-radius:25px;\n"
"font: 15pt \"方正姚体\";\n"
"")
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.receiver_choose = QtWidgets.QComboBox(self.frame)
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.receiver_choose.setFont(font)
        self.receiver_choose.setStyleSheet("border-radius:25px;\n"
"font: 15pt \"方正姚体\";\n"
"background-color: #FFF6EA")
        self.receiver_choose.setObjectName("receiver_choose")
        self.receiver_choose.addItem("")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.receiver_choose)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame_2)
        Client.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Client)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        Client.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Client)
        self.statusbar.setObjectName("statusbar")
        Client.setStatusBar(self.statusbar)

        self.retranslateUi(Client)
        QtCore.QMetaObject.connectSlotsByName(Client)


        # 定义信号函数

        self.exit_button.clicked.connect(Client.close)
        QtCore.QMetaObject.connectSlotsByName(Client)
        self.login_button.clicked.connect(self.log_in)
        self.logout_button.clicked.connect(self.log_out)
        self.send_message_button.clicked.connect(self.sendmess)

        # 定义其他变量
        self.connectFlag = False
        self.socketDict = {}
        self.Client = Client

    def retranslateUi(self, Client):
        _translate = QtCore.QCoreApplication.translate
        Client.setWindowTitle(_translate("Client", "MainWindow"))
        self.label.setText(_translate("Client", "IP："))
        self.label_4.setText(_translate("Client", "Port："))
        self.label_6.setText(_translate("Client", "用户名："))
        self.login_button.setText(_translate("Client", "登录"))
        self.logout_button.setText(_translate("Client", "离线"))
        self.exit_button.setText(_translate("Client", "关闭"))
        self.message_edit.setPlaceholderText(_translate("Client", "在这里输入你要发送的内容"))
        self.send_message_button.setText(_translate("Client", "发送"))
        self.label_5.setText(_translate("Client", "发送给："))
        self.receiver_choose.setItemText(0, _translate("Client", "所有人"))



    def log_in(self):
        if not self.connectFlag:
            self.connectFlag = True
            self.name = "<" + self.username_edit.text() + ">"
            self.socketDict[self.name] = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            self.socketDict[self.name].connect((self.ip_edit.text(), int(self.port_edit.text())))
            self.socketDict[self.name].send(self.name.encode('utf-8'))
            t1 = threading.Thread(target=self.handle, args=())
            t1.start()
            msg = QMessageBox()
            msg.setWindowTitle("提示：")
            msg.setText("登陆成功!")
            msg.setIcon(QMessageBox.Information)
            x = msg.exec_()
        else:
            self.info.append("已经上线")

    def log_out(self):
        if self.connectFlag:
            self.connectFlag = False
            self.socketDict[self.name].send("exit".encode('utf-8'))
            self.socketDict[self.name].close()
            del self.socketDict[self.name]
            self.name = "<anonymous user>"
            msg = QMessageBox()
            msg.setWindowTitle("提示：")
            msg.setText("已下线!")
            msg.setIcon(QMessageBox.Information)
            x = msg.exec_()
        else:
            self.info.append("you are already offline")

    def exit(self):
        # 在关闭客户端时也能够发送消息给服务端，让服务端的线程结束
        if self.connectFlag:
            self.connectFlag = False
            self.socketDict[self.name].send("exit".encode('utf-8'))
            self.socketDict[self.name].close()
        else:
            self.info.append("you are already offline")
        self.Client.Close()

    def sendmess(self):
        if self.connectFlag:
            if self.message_edit.toPlainText() and self.receiver_choose.currentText():
                if self.receiver_choose.currentIndex() == 0:
                    # 选择消息接收者为“all_users”，群发消息
                    self.socketDict[self.name].send(("sendmess_group").encode('utf-8'))
                    self.socketDict[self.name].send((self.name+ "-*-" +
                                                     self.message_edit.toPlainText()).encode('utf-8'))
                else:
                    # 否则，单发消息
                    self.socketDict[self.name].send(("sendmess").encode('utf-8'))
                    self.socketDict[self.name].send(("<" + self.receiver_choose.currentText() + ">" + "-*-" +
                                                     self.message_edit.toPlainText()).encode('utf-8'))

                self.message_edit.clear()

        else:
            self.info.append("下线")


    def handle(self):
        while True:
            if self.connectFlag:
                mode = self.socketDict[self.name].recv(1024).decode('utf-8')

                if mode == "sendmess":
                    messtext = self.socketDict[self.name].recv(1024).decode('utf-8')
                    self.info.insertPlainText(messtext)
                elif mode == "userupdate":
                    messtext = self.socketDict[self.name].recv(1024).decode('utf-8')
                    messtext_split = messtext.split('\n')

                    # 维护目前在线用户信息，并更新可供选择的接收者列表
                    i = 0
                    j = 1
                    while i < len(messtext_split) and j < self.receiver_choose.count():
                        user = messtext_split[i]
                        if user != self.name:
                            user = user.strip('<')
                            user = user.strip('>')
                            self.receiver_choose.setItemText(j, user)
                            j += 1
                        i += 1
                    while i < len(messtext_split):
                        user = messtext_split[i]
                        if user != self.name:
                            user = user.strip('<')
                            user = user.strip('>')
                            self.receiver_choose.addItem(user)
                        i += 1
            else:
                break



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Client = QtWidgets.QMainWindow()
    ui = Ui_Client()
    ui.setupUi(Client)
    Client.show()
    sys.exit(app.exec_())
